name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Cleaning
      run: |
        cd tests
        make clean
    - name: Building
      run: make
